---
hide_body: false
is_partial: false
fields:
- name: Description
  label: Description
  type: text
  hidden: false
  default: ''
- name: Tags
  label: Tags
  type: list
  hidden: false
  default:
  - Development
  - golang
- name: Categories
  label: Categories
  type: list
  hidden: false
  default:
  - Development
  - GoLang
- name: menu
  label: Menu
  type: text
  hidden: true
  default: main
